-- ============================================================
-- E-Commerce Customer Analytics
-- File: 01_customer_base.sql
-- Database: PostgreSQL
--
-- Business Question:
-- How many unique customers are in the dataset?
-- ============================================================
SELECT COUNT(DISTINCT customer_id) As Total_Customer 
FROM online_retail 
WHERE customer_id IS NOT NULL;
-- ============================================================


-- Business Question:
-- How many customers have made more than one distinct purchase?

SELECT COUNT(*) FROM(
SELECT COUNT(DISTINCT invoice) As frequency
FROM online_retail 
WHERE customer_id IS NOT NULL GROUP BY customer_id
) WHERE frequency >1;
-- ============================================================

-- Business Question:
-- What percentage of our customers are repeat customers?

SELECT (
    (
        SELECT COUNT(*)
        FROM (
            SELECT COUNT(DISTINCT invoice) AS frequency
            FROM online_retail
            WHERE customer_id IS NOT NULL
            GROUP BY customer_id
        )
        WHERE frequency > 1
    ) * 100.0
) / (
    SELECT COUNT(DISTINCT customer_id)
    FROM online_retail
    WHERE customer_id IS NOT NULL
);
-- ============================================================
-- Business Question:
-- How many customers made exactly one purchase?

SELECT frequency,
       COUNT(customer_id) AS number_of_customers
FROM (
    SELECT customer_id,
           COUNT(DISTINCT invoice) AS frequency
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
) AS customer_frequency
GROUP BY frequency
HAVING frequency = 1;
-- ============================================================

-- Business Question:
-- What percentage of customers made exactly one purchase?

SELECT ((
    SELECT COUNT(customer_id) AS number_of_customers
    FROM (
        SELECT customer_id,
               COUNT(DISTINCT invoice) AS frequency
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    ) AS customer_frequency
    GROUP BY frequency
    HAVING frequency = 1
) * 100.0) / (
    SELECT COUNT(DISTINCT customer_id)
    FROM online_retail
    WHERE customer_id IS NOT NULL
);

-- ============================================================
-- Business Question:
-- What percentage of total revenue comes from customers
-- with more than one distinct purchase?

SELECT (
    (
        SELECT SUM(all_customer_revenue)
        FROM (
            SELECT SUM(quantity * price) AS all_customer_revenue
            FROM online_retail
            WHERE customer_id IS NOT NULL
            GROUP BY customer_id
            HAVING COUNT(DISTINCT invoice) > 1
        ) AS repeat_customers
    ) * 100.0
) / (
    SELECT SUM(all_customer_revenue)
    FROM (
        SELECT SUM(quantity * price) AS all_customer_revenue
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    ) AS all_customers
);


-- ============================================================
-- Business Question:
-- Who are the top 10 customers by total revenue?

SELECT customer_id,
    SUM(quantity * price) AS total_revenue
FROM online_retail
WHERE customer_id IS NOT NULL
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 10;


-- ============================================================

-- Business Question:
-- What percentage of total revenue is generated by the top 10 customers?

SELECT (((
    SELECT SUM(total_revenue)
    FROM (
        SELECT SUM(quantity * price) AS total_revenue
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
        ORDER BY total_revenue DESC
        LIMIT 10
    )
) * 100) / (
    SELECT SUM(total_revenue)
    FROM (
        SELECT SUM(quantity * price) AS total_revenue
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    )
));


-- ============================================================
-- Business Question:
-- How many customers generate more than £10,000 in total revenue?

SELECT COUNT(*)
FROM (
    SELECT SUM(quantity * price) AS total_revenue
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
    HAVING SUM(quantity * price) > 10000
);


-- ============================================================

-- Business Question:
-- How many customers have made more than one distinct purchase?

SELECT COUNT(*)
FROM (
    SELECT COUNT(DISTINCT invoice)
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
    HAVING COUNT(DISTINCT invoice) > 1
);


-- ============================================================

-- Business Question:
-- What percentage of customers are repeat customers?

SELECT (
    (
        SELECT COUNT(*)
        FROM (
            SELECT COUNT(DISTINCT invoice)
            FROM online_retail
            WHERE customer_id IS NOT NULL
            GROUP BY customer_id
            HAVING COUNT(DISTINCT invoice) > 1
        )
    ) * 100.0
) / (
    SELECT COUNT(*)
    FROM (
        SELECT COUNT(DISTINCT invoice)
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    )
);


-- ============================================================

-- Business Question:
-- What is the distribution of purchase frequency across customers?

SELECT frequency,
       COUNT(customer_id) AS number_of_customers
FROM (
    SELECT customer_id,
           COUNT(DISTINCT invoice) AS frequency
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
) AS customer_frequency
GROUP BY frequency
ORDER BY frequency;

-- ============================================================

-- Business Question:
-- How much revenue was generated each month?

SELECT DATE_TRUNC('MONTH', invoice_date) AS month,
       SUM(quantity * price) AS total_revenue
FROM online_retail
GROUP BY DATE_TRUNC('MONTH', invoice_date)
ORDER BY month ASC;


-- ============================================================
-- Business Question:
-- Which month generated the highest revenue?

SELECT DATE_TRUNC('MONTH', invoice_date) AS month,
       SUM(quantity * price) AS total_revenue
FROM online_retail
GROUP BY DATE_TRUNC('MONTH', invoice_date)
ORDER BY total_revenue DESC
LIMIT 1;


-- ============================================================

-- Business Question:
-- How many unique customers purchased each month?

SELECT DATE_TRUNC('MONTH', invoice_date) AS month,
       COUNT(DISTINCT customer_id) AS unique_customers
FROM online_retail
WHERE customer_id IS NOT NULL
GROUP BY DATE_TRUNC('MONTH', invoice_date)
ORDER BY month;


-- ============================================================

-- Business Question:
-- What was the average revenue per customer each month?

SELECT DATE_TRUNC('MONTH', invoice_date) AS month,
       SUM(quantity * price) / COUNT(DISTINCT customer_id) AS avg_revenue_per_customer
FROM online_retail
WHERE customer_id IS NOT NULL
GROUP BY DATE_TRUNC('MONTH', invoice_date)
ORDER BY month;

-- ============================================================

-- Business Question:
-- How can customers be classified into low-, medium-, and high-value segments based on total revenue?

SELECT customer_id,
       total_revenue,
       CASE
           WHEN total_revenue < 1000 THEN 'Low'
           WHEN total_revenue <= 10000 THEN 'Medium'
           ELSE 'High'
       END AS segment
FROM (
    SELECT customer_id,
           SUM(quantity * price) AS total_revenue
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
) AS customer_revenue;


-- ============================================================

-- Business Question:
-- How many customers are in each revenue segment (Low, Medium, High)?

SELECT segment, COUNT(DISTINCT customer_id) AS number_of_customers,
FROM (
    SELECT customer_id,
           total_revenue,
           CASE
               WHEN total_revenue < 1000 THEN 'Low'
               WHEN total_revenue <= 10000 THEN 'Medium'
               ELSE 'High'
           END AS segment
    FROM (
        SELECT customer_id,
               SUM(quantity * price) AS total_revenue
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    ) AS customer_revenue
) AS customer_segments
GROUP BY segment;

-- ============================================================
-- Business Question:
-- What percentage of customers belong to each revenue segment?
-- Solution 1: Using a scalar subquery

SELECT segment,
       COUNT(DISTINCT customer_id) AS number_of_customers,
       (COUNT(DISTINCT customer_id) * 100.0) /
       (
           SELECT COUNT(DISTINCT customer_id)
           FROM online_retail
           WHERE customer_id IS NOT NULL
       ) AS percentage
FROM (
    SELECT customer_id,
           total_revenue,
           CASE
               WHEN total_revenue < 1000 THEN 'Low'
               WHEN total_revenue <= 10000 THEN 'Medium'
               ELSE 'High'
           END AS segment
    FROM (
        SELECT customer_id,
               SUM(quantity * price) AS total_revenue
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    ) AS customer_revenue
) AS customer_segments
GROUP BY segment;

-- Business Question:
-- What percentage of customers belong to each revenue segment?
-- Solution 1: Using a scalar subquery

SELECT segment,
       COUNT(DISTINCT customer_id) AS number_of_customers,
       (COUNT(DISTINCT customer_id) * 100.0) /
       (
           SELECT COUNT(DISTINCT customer_id)
           FROM online_retail
           WHERE customer_id IS NOT NULL
       ) AS percentage
FROM (
    SELECT customer_id,
           total_revenue,
           CASE
               WHEN total_revenue < 1000 THEN 'Low'
               WHEN total_revenue <= 10000 THEN 'Medium'
               ELSE 'High'
           END AS segment
    FROM (
        SELECT customer_id,
               SUM(quantity * price) AS total_revenue
        FROM online_retail
        WHERE customer_id IS NOT NULL
        GROUP BY customer_id
    ) AS customer_revenue
) AS customer_segments
GROUP BY segment;

Solution 1 → Scalar subquery
             ↓
             Gets total customers separately

Solution 2 → Window function
             ↓
             SUM(number_of_customers) OVER ()
             calculates the total while keeping each segment row

-- ============================================================

-- Business Question:
-- Which years are present in the dataset, and how many transactions occurred in each year?

SELECT EXTRACT(YEAR FROM invoice_date) AS year,
       COUNT(*) AS transactions
FROM online_retail
GROUP BY EXTRACT(YEAR FROM invoice_date);

-- ============================================================

-- Business Question:
-- How much revenue was generated in each month of the year,
-- regardless of which year it was?

SELECT EXTRACT(MONTH FROM invoice_date) AS month,
       SUM(quantity * price) AS total_revenue
FROM online_retail
GROUP BY EXTRACT(MONTH FROM invoice_date)
ORDER BY month ASC;

-- ============================================================

-- Business Question:
-- How did monthly revenue compare with the previous month?

SELECT month,
       total_revenue,
       LAG(total_revenue) OVER (ORDER BY month) AS previous_month_revenue
FROM (
    SELECT EXTRACT(MONTH FROM invoice_date) AS month,
           SUM(quantity * price) AS total_revenue
    FROM online_retail
    GROUP BY EXTRACT(MONTH FROM invoice_date)
) AS monthly_revenue
ORDER BY month ASC;
-- ============================================================
-- Business Question:
-- How much did monthly revenue increase or decrease compared with the previous month?

SELECT month,
       total_revenue,
       previous_month_revenue,
       total_revenue - previous_month_revenue AS revenue_change
FROM (
    SELECT month,
           total_revenue,
           LAG(total_revenue) OVER (ORDER BY month) AS previous_month_revenue
    FROM (
        SELECT EXTRACT(MONTH FROM invoice_date) AS month,
               SUM(quantity * price) AS total_revenue
        FROM online_retail
        GROUP BY EXTRACT(MONTH FROM invoice_date)
    ) AS monthly_revenue
) AS monthly_comparison
ORDER BY month ASC;
-- ============================================================
-- Business Question:
-- What will the revenue be in the following month?

SELECT month,
       total_revenue,
       LEAD(total_revenue) OVER (ORDER BY month) AS next_month_revenue
FROM (
    SELECT EXTRACT(MONTH FROM invoice_date) AS month,
           SUM(quantity * price) AS total_revenue
    FROM online_retail
    GROUP BY EXTRACT(MONTH FROM invoice_date)
) AS monthly_revenue
ORDER BY month ASC;
-- ============================================================
/*
Business Question:
Find customers whose total spending is greater than the average
spending of all customers.
*/

WITH customer_spending AS (
    SELECT customer_id,
           SUM(quantity * price) AS total_spending
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
)

SELECT customer_id,
       total_spending
FROM customer_spending
WHERE total_spending > (
    SELECT AVG(total_spending)
    FROM customer_spending
);

-- ============================================================

/*
Business Question:
Find the top 10 customers by total spending.
*/

WITH customer_spending AS (
    SELECT customer_id,
           SUM(quantity * price) AS total_spending
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
)

SELECT customer_id,
       total_spending
FROM customer_spending
ORDER BY total_spending DESC
LIMIT 10;

-- ============================================================

/*
Business Question:
Find the top 5 countries by total revenue.
*/

WITH country_revenue AS (
    SELECT country,
           SUM(quantity * price) AS total_revenue
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY country
)

SELECT country,
       total_revenue
FROM country_revenue
ORDER BY total_revenue DESC
LIMIT 5;

-- ============================================================
/*
Business Question:
Find the top 5 customers by total spending,
but only include customers who have made at least 5 purchases.
*/

WITH customer_spending AS (
    SELECT customer_id,
           SUM(quantity * price) AS total_revenue,
           COUNT(stock_code) AS number_of_purchases
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
)

SELECT customer_id,
       total_revenue
FROM customer_spending
WHERE number_of_purchases >= 5
ORDER BY total_revenue DESC
LIMIT 5;
-- ===========================================================

/*
Business Question:
Find customers whose total spending is higher than the 
average spending of customers from the United Kingdom.
*/

WITH customer_spending AS (
    SELECT customer_id, SUM(quantity*price) AS total_spending
    FROM online_retail
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id
)
SELECT customer_id, total_spending
FROM customer_spending
WHERE total_spending > (
    SELECT AVG(total_spending) FROM(
    SELECT customer_id, SUM(quantity*price) AS total_spending
    FROM online_retail
    WHERE customer_id IS NOT NULL AND country = 'United Kingdom'
    GROUP BY customer_id
    ) AS uk_customer
);

-- ============================================================

SELECT
    customer_id, invoice, invoice_date,
    ROW_NUMBER() OVER(
        PARTITION BY customer_id
        ORDER BY invoice_date
    ) AS purchase_number
FROM online_retail
WHERE customer_id IS NOT NULL;

-- ============================================================

SELECT
    customer_id,
    SUM(quantity * price) AS total_spending,
    RANK() OVER (
        ORDER BY SUM(quantity * price) DESC
    ) AS rank,
    DENSE_RANK() OVER (
        ORDER BY SUM(quantity * price) DESC
    ) AS dense_rank
FROM online_retail
WHERE customer_id IS NOT NULL
GROUP BY customer_id;


-- ============================================================

/*
Business Question:
For each customer's purchase, show the previous purchase date.
*/

SELECT
    customer_id,
    invoice_date,
    LAG(invoice_date) OVER (
        PARTITION BY customer_id
        ORDER BY invoice_date ASC
    ) AS previous_purchase_date
FROM online_retail
WHERE customer_id IS NOT NULL;


/*
Business Question:
For each customer's purchase, show the previous purchase date.
*/

SELECT
    customer_id,
    invoice_date,
    LAG(invoice_date) OVER (
        PARTITION BY customer_id
        ORDER BY invoice_date ASC
    ) AS previous_purchase_date
FROM online_retail
WHERE customer_id IS NOT NULL;

-- ============================================================

/*
Business Question:
For each customer, calculate the number of days between
their current purchase and their previous purchase.
*/

WITH customer_purchases AS (
    SELECT
        customer_id,
        invoice_date,
        LAG(invoice_date) OVER (
            PARTITION BY customer_id
            ORDER BY invoice_date
        ) AS previous_purchase_date
    FROM online_retail
    WHERE customer_id IS NOT NULL
)

SELECT
    customer_id,
    invoice_date,
    previous_purchase_date,
    invoice_date - previous_purchase_date AS days_since_previous
FROM customer_purchases;


-- ============================================================
/*
Business Question:
For each customer, show their current purchase date
and the date of their next purchase.
*/

SELECT
    customer_id,
    invoice_date,
    LEAD(invoice_date) OVER (
        PARTITION BY customer_id
        ORDER BY invoice_date
    ) AS next_purchase_date
FROM online_retail
WHERE customer_id IS NOT NULL;

-- ============================================================

/*
Business Question:
For each customer, calculate the number of days until
their next purchase.
*/

WITH customer_purchases AS (
    SELECT
        customer_id,
        invoice_date,
        LEAD(invoice_date) OVER (
            PARTITION BY customer_id
            ORDER BY invoice_date
        ) AS next_purchase_date
    FROM online_retail
    WHERE customer_id IS NOT NULL
)

SELECT
    customer_id,
    invoice_date,
    next_purchase_date,
    next_purchase_date - invoice_date AS days_until_next_purchase
FROM customer_purchases;

-- ============================================================
/*
Business Question:
Find the number of users in each tweet-count bucket for 2022.
*/


WITH tweet_data AS (
    SELECT user_id, COUNT(tweet_id) AS tweet_bucket
    FROM tweets
    WHERE tweet_date >= '2022-01-01'
    AND tweet_date < '2023-01-01'
    GROUP BY user_id
)

SELECT tweet_bucket, COUNT(user_id)
FROM tweet_data
GROUP BY tweet_bucket;




-- ============================================================
-- ============================================================
-- ============================================================
-- ============================================================
-- ============================================================
-- ============================================================

-- ============================================================